version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addin
  - asyncio
  - asyncloop
  - designpilot
  - dpapp
  - fcompute
  - fdefault
  - fdel
  - Fireable
  - fref
  - fromlist
  - fusionbase
  - levelno
  - onclick
  - pyright
  - pytest
  - pythonpath
  - rxprop
  - setuptools
ignoreWords: []
import: []
