version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addin
  - asyncio
  - asyncloop
  - caseconverter
  - designpilot
  - dpapp
  - fcompute
  - fdefault
  - fdel
  - Fireable
  - fref
  - fromlist
  - fusionbase
  - invalidator
  - invalidators
  - levelno
  - mypy
  - onclick
  - pyright
  - pytest
  - pythonpath
  - rxprop
  - setuptools
  - snakecase
  - unregisters
  - watchf
  - watchp
ignoreWords: []
import: []
