version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addin
  - asyncloop
  - designpilot
  - dpapp
  - fcompute
  - fdefault
  - fdel
  - Fireable
  - fref
  - fromlist
  - fusionbase
  - levelno
  - onclick
ignoreWords: []
import: []
