version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addin
  - asyncio
  - asyncloop
  - caseconverter
  - designpilot
  - dpapp
  - envsubst
  - fcompute
  - fdefault
  - fdel
  - Fireable
  - followlinks
  - fref
  - fromlist
  - fusionbase
  - invalidator
  - invalidators
  - jobject
  - kebabcase
  - keepalive
  - levelno
  - litellm
  - mypy
  - onclick
  - pchangenotifier
  - pyright
  - pytest
  - pythonpath
  - reactivelist
  - rxprop
  - searchpath
  - setuptools
  - snakecase
  - Taskfile
  - unregisters
  - vars
  - watchf
  - watchp
ignoreWords: []
import: []
